spring.application.name=astro-api
spring.config.import=optional:file:.env[.properties]
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

management.opentelemetry.resource-attributes.service.name=astro-api
management.otlp.metrics.export.enabled=false
management.tracing.export.otlp.enabled=false
management.logging.export.otlp.enabled=false

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.maximum-pool-size=${POSTGRES_MAX_POOL_SIZE:3}
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}

storage.r2.endpoint=${R2_ENDPOINT:}
storage.r2.bucket=${R2_BUCKET:${R2_BUCKET_AVATARS:}}
storage.r2.access-key-id=${R2_ACCESS_KEY_ID:}
storage.r2.secret-access-key=${R2_SECRET_ACCESS_KEY:}
storage.r2.presigned-url-duration=${R2_PRESIGNED_URL_DURATION:1d}
